version: '3.8'
services:
  flask_web: #1st container 
    build: .   #building like docker build .
    image: flask_web #image_name
    ports:
      #- 5656:5656
      - 5000:5000
    environment:
      - MONGO_HOST=mongo  #space not allowed here like Mongo_host = mongo
      - MONGO_PORT=27017
    networks:
      - main_net 
    depends_on:
      - mongodb

  mongodb: #2nd container
    #light image use for personal cost perspective 
    image: mvertes/alpine-mongo
    #image: mongo
    restart: always
    hostname: test_mongodb
    ports:
      - 27017:27017
    networks:
      - main_net

#networks services here
networks:
  main_net:
    driver: bridge