apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp

spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: rabadiyanikunj436/py_aws
          ports:
            - containerPort: 5000
          imagePullPolicy: Always 