apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp

spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: rabadiyanikunj436/py_aws:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000 