apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
spec:
  selector:
    app: webapp
  ports:
    - port: 8080 #service port
      targetPort: 5000 #where it should go (in this case container port )
  type: LoadBalancer 